[package]
name = "tower-hyper"
version = "0.1.0"
authors = ["Lucio Franco <luciofranco14@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.1"
http = "0.1"
log = "0.4"
hyper = "0.12.21"
tokio-io = "0.1"
tokio-buf = "0.1"
tokio-executor = "0.1"
tower-service = "0.2"
tower = { git = "https://github.com/tower-rs/tower" }
tower-http = { git = "https://github.com/tower-rs/tower-http" }

[dev-dependencies]
tower-buffer = { git = "https://github.com/tower-rs/tower" }
tokio-executor = "0.1"
tokio-tcp = "0.1"
pretty_env_logger = "0.2.0"
