[package]
name = "tower-hyper"
version = "0.1.0"
authors = ["Lucio Franco <luciofranco14@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.1"
http = "0.1"
hyper = "0.12.21"
log = "0.4"
tokio-io = "0.1"
tower-service = { git = "https://github.com/tower-rs/tower" }
tower-retry = { git = "https://github.com/tower-rs/tower" }
tower-direct-service = { git = "https://github.com/tower-rs/tower" }
tower-util = { git = "https://github.com/tower-rs/tower" }

[dev-dependencies]
tower-buffer = { git = "https://github.com/tower-rs/tower" }
tokio-executor = "0.1"
pretty_env_logger = "0.2.0"